### PR TITLE
Add chromium browser type

### PR DESCRIPTION
**Pull request by tao-lian**
Using CEFSharp 75.1.142 (Chromium 75.0.3770.100)

Change default browser type to "chrome"
<BrowserType>chrome</BrowserType>

Users can switch back to IE browser type by setting <BrowserType>ie</BrowserType>

### CODE REVIEW

**Comment by dasgarner** [comment]
Thank you for your contribution - we will do our best to test it out next week. We can look at adding the BrowserType setting CMS side also.

In the meantime are you able to [sign our CLA](https://github.com/xibosignage/xibo/blob/master/CONTRIBUTING.md)?

**Comment by tao-lian** [comment]
Hi @dasgarner 

Yes, I can confirm this contribution is authored by me and I am happy to grant irrevocable to the Users, the Contributors, and Spring Signage Ltd. But I don't want to share my personal details like home address or phone numbers, hopefully it is OK.

**Comment by dasgarner** [comment]
Hi, yes I am sure that will be fine, thank you.

The code looks good, switching between Browser Types seems fine and the test i've got renders well. 

Changing between Layouts or Media fails though, with an Access Violation:

``
Audit: <logdate>2019-10-02 07:59:08</logdate><thread>UI Thread</thread><method>MainForm - DestoryLayout</method><message>Calling Dispose on Region 2424</message>
Region: Removing media on region dispose
IeWebMedia - Dispose: Disposing of C:\Users\Dan\Documents\Xibo Library\4906.htm
Region - Dispose: Media Disposed by Region
HardwareKey: [IN]
HardwareKey: [OUT]
MainForm - Prepare Layout: Created new region
Audit: <logdate>2019-10-02 07:59:08</logdate><thread>UI Thread</thread><method>Region - SetNextMediaNode</method><message>New media detected webpage</message>
Audit: <logdate>2019-10-02 07:59:08</logdate><thread>UI Thread</thread><method>Region - CreateNextMediaNode</method><message>Creating new media: webpage, 4688</message>
The program '[13856] XiboClient.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.
```

**Comment by tao-lian** [comment]
> Hi, yes I am sure that will be fine, thank you.
> 
> The code looks good, switching between Browser Types seems fine and the test i've got renders well.
> 
> Changing between Layouts or Media fails though, with an Access Violation:
> 
> ```
> Audit: <logdate>2019-10-02 07:59:08</logdate><thread>UI Thread</thread><method>MainForm - DestoryLayout</method><message>Calling Dispose on Region 2424</message>
> Region: Removing media on region dispose
> IeWebMedia - Dispose: Disposing of C:\Users\Dan\Documents\Xibo Library\4906.htm
> Region - Dispose: Media Disposed by Region
> HardwareKey: [IN]
> HardwareKey: [OUT]
> MainForm - Prepare Layout: Created new region
> Audit: <logdate>2019-10-02 07:59:08</logdate><thread>UI Thread</thread><method>Region - SetNextMediaNode</method><message>New media detected webpage</message>
> Audit: <logdate>2019-10-02 07:59:08</logdate><thread>UI Thread</thread><method>Region - CreateNextMediaNode</method><message>Creating new media: webpage, 4688</message>
> The program '[13856] XiboClient.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.
> ```
> 
> EDIT: I should have said that the same Layout works well on change with `<BrowserType>browsercontrol</BrowserType>`

Interesting!! With WebMedia factory, if browsertype = chrome, it should only create an object of CefWebMedia, but in your log it has disposing of IeWebMedia. 

Another thought is, CEF created separate thread to run chromium. If the application tries to access it directly, it is like to have memory access denied. The only way to interactive with it is using invoke. I am wondering would Access Violation is related to this. 

I am quite busy in work this week, will try to get sometime this weekend to see if I can find some solution.

**Comment by dasgarner** [comment]
> CefWebMedia, but in your log it has disposing of IeWebMedia.

I think this is just a log message in CefWebMedia

> I am quite busy in work this week, will try to get sometime this weekend to see if I can find some solution.

Sure, no rush at all - thanks for any help!

**Comment by tao-lian** [comment]
@dasgarner 

The issue was the CEF should not be re-initialized. The framework needs to be initialized once while main form loading, and shutdown when closing. The browser object will be created on every HTML/Web layout loading, and dispose after using.

**Comment by dasgarner** [comment]
Thanks, i'll get that tested.

Just so you are aware - we will make a release v2 R201 ahead of making large changes like this, which we will put in R202 and follow shortly after.

**Comment by dasgarner** [comment]
Would your use-case be solved by the Edge browser instead of the Chromium browser?

I ask because we have had some success putting the edge browser into the Player and it keeps the file size much smaller (with Chromium the file size is > 120MB, but with Edge it is 6MB).

You can see the work we've done here: https://github.com/dasgarner/xibo-dotnetclient/tree/feature/webview - it was inspired by what you did in this PR, with a few small changes around how you implemented the selection of the browser

**Comment by LaurentPointCa** [comment]
Hi! I tested the PR and it seems that the media timer is not resetting properly so that the layouts don't cycle. Is this an issue you've observed on your end? It might have nothing to do with your changes, but before finding your pull request, I did my own integration of Chromium (although a bit differently) and I had the very same timer bug to fix, so perhaps they're linked.

**Comment by tao-lian** [comment]
@dasgarner sorry about the slow respond, and yes, if edge can be integrated with player, it would help the most cases. Will you support chromium based Edge or the "normal" edge?

**Comment by tao-lian** [comment]
Hi, @LaurentPointCa. The layout cycle seems working ok to me, how could I find out if I have "media timer" issue?

**Comment by dasgarner** [comment]
> @dasgarner sorry about the slow respond, and yes, if edge can be integrated with player, it would help the most cases. Will you support chromium based Edge or the "normal" edge?

It would be normal edge for the time being - but as the library gets updated we would pull those updates into the Player, so I would expect it to be chrome edge in due course.

Are you happy to test the branch I linked above? If it solves your problem I think we should take that direction instead.

You definitely inspired the edge solution, so thank you!

**Comment by tao-lian** [comment]
Hi @dasgarner 

I have tested the edge branch, the good news is the pages are rendered correctly, layout, animations etc. The bad news is, for some reason, it blocks other widgets in the same layout. By "block", I mean those widgets simply not be displayed at all. I have tried to change z-index, which does not fix it. The overlay layout can be displayed correct though. Any ideas?

Cheers
Tao

**Comment by dasgarner** [comment]
Interesting - that isn't something we've had reported during testing. Are your Regions overlapping at all?

I'm happy to test your Layout if you're able to provide a sample? you can upload to https://transfer.xibo.org.uk and send me the link

**Comment by tao-lian** [comment]
Hi @dasgarner 

My layout needs to access an internal server for html content, so wont work outside our network.

However I have uploaded a screenshot of layout. In short, the big box on the left is HTML widget, and on the right, it is (in top-down order) title text, calendar to google, title text, calendar to google. At the bottom, it is space reversed for overly, which is a RSS news.

When using edge as browser type, the right column is empty. But both html page and rss news displayed.

Untitled

**Pull request closed without merging**
